config/routes.rb
Leis::Application.routes.draw do

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/area.rb
# == Schema Information
#
# Table name: areas
#
#  id         :integer          not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Area < ActiveRecord::Base
  attr_accessible :content

  # has_many :atribuicaos, foreign_key: "area_id", dependent: :destroy

  has_many :atribuicaos, foreign_key: "area_id", dependent: :destroy
  has_many :reverse_atribuicaos, class_name: :Atribuicao
	has_many :verbos, :through => :atribuicaos, :source => :verbo #. Is it one of :verbos or :areas?

	before_save { self.content = self.content.downcase.strip.gsub("  "," ") }

	validates :content, presence: true, length: { minimum: 2 }

end

# v = Verbo.create content: "  teste  Verbo9 "
# a = Area.create content: "  teste  Area9 "
# a.verbos = [v]
# a.atribuicaos

app/models/assunto.rb
# == Schema Information
#
# Table name: assuntos
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Assunto < ActiveRecord::Base
  attr_accessible :content
end

app/models/atribuicao.rb
# == Schema Information
#
# Table name: atribuicaos
#
#  id         :integer          not null, primary key
#  verbo_id   :integer
#  area_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Atribuicao < ActiveRecord::Base
  attr_accessible :area_id, :verbo_id

  belongs_to :verbo
  belongs_to :area

  has_many :classe_atribuicaos, foreign_key: "atribuicao_id", dependent: :destroy
  has_many :reverse_classe_atribuicaos, class_name: :ClasseAtribuicao
	has_many :classes, :through => :classe_atribuicaos, :source => :classe 

  has_many :cargo_atribuicaos, foreign_key: "atribuicao_id", dependent: :destroy
  has_many :reverse_cargo_atribuicaos, class_name: :CargoAtribuicao
	has_many :cargos, :through => :cargo_atribuicaos, :source => :cargo 

end

app/models/att.rb
# == Schema Information
#
# Table name: atts
#
#  id         :integer          not null, primary key
#  area       :text
#  v1         :string(255)
#  v2         :string(255)
#  v3         :string(255)
#  v4         :string(255)
#  v5         :string(255)
#  v6         :string(255)
#  v7         :string(255)
#  v8         :string(255)
#  v9         :string(255)
#  apf        :boolean
#  epf        :boolean
#  ppf        :boolean
#  opf        :boolean
#  dpf        :boolean
#  pcf        :boolean
#  clesp      :boolean
#  cl1        :boolean
#  cl2        :boolean
#  cl3        :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Att < ActiveRecord::Base
  attr_accessible :apf, :area, :cl1, :cl2, :cl3, :clesp, :dpf, :epf, :opf, :pcf, :ppf, :v1, :v2, :v3, :v4, :v5, :v6, :v7, :v8, :v9
end

app/models/cargo.rb
# == Schema Information
#
# Table name: cargos
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cargo < ActiveRecord::Base
  attr_accessible :content

  has_many :cargo_atribuicaos, foreign_key: "cargo_id", dependent: :destroy
  has_many :reverse_cargo_atribuicaos, class_name: :CargoAtribuicao
	has_many :atribuicaos, :through => :cargo_atribuicaos, :source => :atribuicao 

 	before_save { self.content = self.content.downcase.strip.gsub("  "," ") }
 	
end

# a = Atribuicao.find(775) # (find, create, etc...)
# c = Cargo.find_by_content("OPF") #(find, .create content: "  teste  Area9 "
# c.atribuicaos = [a]
# c.cargo_atribuicaos

app/models/cargo_atribuicao.rb
# == Schema Information
#
# Table name: cargo_atribuicaos
#
#  id            :integer          not null, primary key
#  cargo_id      :integer
#  atribuicao_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class CargoAtribuicao < ActiveRecord::Base
  attr_accessible :atribuicao_id, :cargo_id

  belongs_to :atribuicao
  belongs_to :cargo  
end

app/models/classe.rb
# == Schema Information
#
# Table name: classes
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Classe < ActiveRecord::Base
  attr_accessible :content

  has_many :classe_atribuicaos, foreign_key: "classe_id", dependent: :destroy
  has_many :reverse_classe_atribuicaos, class_name: :ClasseAtribuicao
	has_many :atribuicaos, :through => :classe_atribuicaos, :source => :atribuicao 

 	before_save { self.content = self.content.downcase.strip.gsub("  "," ") }
end

# a = Atribuicao.find(775) 
# aa = Atribuicao.find(776) 
# c = Classe.find_by_content("Especial") 
# c.atribuicaos = [a, aa]	
# c.classe_atribuicaos

# cc = Classe.find_by_content("2") 
# a.classes = [cc]	

app/models/classe_atribuicao.rb
# == Schema Information
#
# Table name: classe_atribuicaos
#
#  id            :integer          not null, primary key
#  classe_id     :integer
#  atribuicao_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class ClasseAtribuicao < ActiveRecord::Base
  attr_accessible :atribuicao_id, :classe_id

  belongs_to :atribuicao
  belongs_to :classe  
end

app/models/verbo.rb
# == Schema Information
#
# Table name: verbos
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Verbo < ActiveRecord::Base
  attr_accessible :content

  has_many :atribuicaos, foreign_key: "verbo_id", dependent: :destroy
  has_many :reverse_atribuicaos, class_name: :Atribuicao
  has_many :areas, through: :atribuicaos, source: :area

	before_save { self.content = self.content.downcase.strip.gsub("  "," ") }

	validates :content, presence: true, length: { minimum: 2 }

  def seguindo?(area)
    atribuicaos.find_by_area_id(area.id)
  end

  def seguir!(area)
    atribuicaos.find_or_create_by_area_id!(area.id)
  end  

  def retirar!(area)
    atribuicaos.find_by_area_id(area.id).destroy
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Projeto de Organizador de Textos de Lei"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    por Vladimir Brasil
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>      
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/_home_signed.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>    
    <section>
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>  
  <div class="span8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>  
</div> 

app/views/static_pages/_home_unsigned.html.erb
<% provide(:title, 'Home') %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Vladimir Brasil
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Ajuda
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Projeto de Organizador de Textos de Lei</h1>
<p>
  Esta é a página inicial deste projeto.
</p>